import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { simpleGit } from 'simple-git';
import { GlobalStore } from '../core/store.js';

export interface UseOptions {
  skill?: string;
}

function parsePackageRef(identifier: string): { raw: string; ref?: string } {
  const atIndex = identifier.lastIndexOf('@');
  if (atIndex > 0 && !identifier.slice(atIndex + 1).includes('/')) {
    return { raw: identifier.slice(0, atIndex), ref: identifier.slice(atIndex + 1) };
  }
  return { raw: identifier };
}

async function resolvePluginDir(identifier: string): Promise<{ dir: string; cleanup: () => Promise<void> }> {
  const localPath = path.resolve(identifier);
  const localExists = await fs.access(localPath).then(() => true).catch(() => false);
  if (localExists) {
    return { dir: localPath, cleanup: async () => {} };
  }

  const parsed = GlobalStore.parseRepoIdentifier(identifier);
  const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'plugins-use-'));
  const cloneDir = path.join(tempDir, 'repo');
  try {
    const git = simpleGit();
    const options = ['--depth', '1'];
    if (parsed.ref && parsed.ref !== 'latest') {
      options.push('--branch', parsed.ref);
    }
    await git.clone(parsed.cloneUrl, cloneDir, options);

    let dir = cloneDir;
    if (parsed.subfolder) {
      const sub = path.join(cloneDir, parsed.subfolder);
      if (await fs.access(sub).then(() => true).catch(() => false)) {
        dir = sub;
      }
    }
    return { dir, cleanup: async () => { await fs.rm(tempDir, { recursive: true, force: true }).catch(() => {}); } };
  } catch (err) {
    await fs.rm(tempDir, { recursive: true, force: true }).catch(() => {});
    throw err;
  }
}

async function readJson(dir: string, file: string): Promise<any | null> {
  const p = path.join(dir, file);
  const exists = await fs.access(p).then(() => true).catch(() => false);
  if (!exists) return null;
  try {
    return JSON.parse(await fs.readFile(p, 'utf8'));
  } catch {
    return null;
  }
}

export async function useCommand(identifier: string, options: UseOptions = {}): Promise<void> {
  const { raw, ref } = parsePackageRef(identifier);
  const resolved = await resolvePluginDir(raw);

  try {
    const pluginJson = (await readJson(resolved.dir, 'plugin.json')) ||
      (await readJson(path.join(resolved.dir, '.claude-plugin'), 'plugin.json')) ||
      (await readJson(path.join(resolved.dir, '.codex-plugin'), 'plugin.json'));
    const mcpJson = await readJson(resolved.dir, 'mcp.json') || await readJson(resolved.dir, '.mcp.json');

    const pluginName = pluginJson?.name || path.basename(resolved.dir);
    const pluginVersion = pluginJson?.version || 'latest';
    const description = pluginJson?.description || '';

    const skillsDir = path.join(resolved.dir, 'skills');
    const skillNames: string[] = [];
    if (await fs.access(skillsDir).then(() => true).catch(() => false)) {
      const entries = await fs.readdir(skillsDir, { withFileTypes: true });
      for (const entry of entries) {
        if (entry.isDirectory()) {
          const skillMd = path.join(skillsDir, entry.name, 'SKILL.md');
          if (await fs.access(skillMd).then(() => true).catch(() => false)) {
            skillNames.push(entry.name);
          }
        }
      }
    }

    const selectedSkill = options.skill
      ? skillNames.find((s) => s === options.skill || (options.skill ? s.includes(options.skill) : false))
      : undefined;

    const lines: string[] = [];
    lines.push(`# Use Plugin: ${pluginName}${pluginVersion ? `@${pluginVersion}` : ''}`);
    if (description) lines.push('');
    lines.push(description || '');
    lines.push('');
    lines.push('## What it provides');
    lines.push(`- Skills: ${skillNames.length > 0 ? skillNames.join(', ') : 'none'}`);
    if (mcpJson?.mcpServers) {
      lines.push(`- MCP servers: ${Object.keys(mcpJson.mcpServers).join(', ')}`);
    }
    lines.push('');

    if (selectedSkill) {
      lines.push(`## Skill: ${selectedSkill}`);
      lines.push('');
      const skillContent = await fs.readFile(path.join(skillsDir, selectedSkill, 'SKILL.md'), 'utf8');
      lines.push(skillContent.trim());
    } else if (skillNames.length === 1) {
      lines.push(`## Skill: ${skillNames[0]}`);
      lines.push('');
      const skillContent = await fs.readFile(path.join(skillsDir, skillNames[0]!, 'SKILL.md'), 'utf8');
      lines.push(skillContent.trim());
    } else {
      lines.push('## How to use');
      lines.push('1. Add the plugin: `plugins add <package>`');
      lines.push(`2. Enable it: \`plugins enable ${pluginName}\``);
      if (skillNames.length > 1) {
        lines.push(`3. Pick a skill: \`plugins use <package>@<skill>\``);
      }
      lines.push('');
      lines.push('Generated by the plugins CLI. Add, enable, then invoke its skills with your agent.');
    }

    console.log(lines.join('\n'));
    if (ref && !selectedSkill) {
      console.log(`\n# Selected package ref: ${ref}`);
    }
  } finally {
    await resolved.cleanup();
  }
}
