import path from 'node:path';
import os from 'node:os';
import { BaseAgentAdapter } from './base.js';
import type { PortableCoreIR, ConversionResult, FileOutput } from '../ir/types.js';
import { rewriteMcpServer } from '../core/mcp-rewriter.js';

import { findWorkspaceRoot } from '../core/config.js';

export class PiAdapter extends BaseAgentAdapter {
  name = 'pi';
  displayName = 'Pi Coding Agent';
  protected override logTag = 'PiAdapter';

  override get detectProbes(): { global: string[]; local: string[] } {
    return {
      global: [path.join(os.homedir(), '.pi')],
      local: [path.join(process.cwd(), '.pi')],
    };
  }

  get globalPluginDir(): string {
    return path.join(os.homedir(), '.pi', 'agent', 'extensions');
  }

  get localPluginDir(): string {
    return path.join(findWorkspaceRoot(), '.pi', 'extensions');
  }

  override get candidateSearchDirs(): { global: string[]; local: string[] } {
    return {
      global: [path.join(os.homedir(), '.pi', 'agent', 'extensions')],
      local: [path.join(process.cwd(), '.pi', 'extensions')],
    };
  }

  capabilities(): string[] {
    return ['skills', 'mcp', 'hooks', 'agents', 'commands'];
  }

  convert(ir: PortableCoreIR, _scope: 'workspace' | 'global'): ConversionResult {
    const files: FileOutput[] = [];
    const warnings: string[] = [...(ir.warnings || [])];
    const manualSteps: string[] = [];
    const { extensions } = ir;
    const storePath = ir.source.resolvedPath || process.cwd();

    // 1. Emit Skills under skills/<name>/SKILL.md
    for (const skill of ir.skills) {
      files.push({
        relativePath: `skills/${skill.name}/SKILL.md`,
        content: `# ${skill.name}\n\n${skill.description ? `${skill.description}\n\n` : ''}${skill.body}`,
        description: `Skill: ${skill.name}`,
      });
    }

    // Convert commands to skills for Pi
    for (const cmd of extensions.commands) {
      files.push({
        relativePath: `skills/${cmd.name}/SKILL.md`,
        content: `# ${cmd.name}\n\n${cmd.description ? `${cmd.description}\n\n` : ''}${cmd.body}`,
        description: `Upgraded Command to Skill for Pi: ${cmd.name}`,
      });
    }

    // 2. Emit MCP config with absolute path expansion -> mcp.json
    if (ir.mcpServers.length > 0) {
      const mcpConfig: Record<string, unknown> = {};
      for (const server of ir.mcpServers) {
        const rewritten = rewriteMcpServer(server, {
          pluginStorePath: storePath,
          targetProvider: 'pi',
        });
        mcpConfig[server.name] = {
          ...(rewritten.command !== undefined ? { command: rewritten.command } : {}),
          ...(rewritten.args !== undefined ? { args: rewritten.args } : {}),
          ...(rewritten.env !== undefined ? { env: rewritten.env } : {}),
          ...(rewritten.cwd !== undefined ? { cwd: rewritten.cwd } : {}),
        };
      }
      files.push({
        relativePath: 'mcp.json',
        content: JSON.stringify(mcpConfig, null, 2),
        description: 'MCP server configuration (.pi/mcp.json)',
      });
    }

    // 3. Synthesize TypeScript Extension Wrapper (index.ts) per ADR 0025
    const extensionLines: string[] = [];
    extensionLines.push('// Generated by agentpm - Pi Agent Extension Wrapper (ADR 0025)');
    extensionLines.push('export default function (pi: any) {');

    // Register skills with /skill: prefix
    const allSkillNames = [...ir.skills.map((s) => s.name), ...extensions.commands.map((c) => c.name)];
    for (const skillName of allSkillNames) {
      extensionLines.push(`  pi.registerSkill({ name: ${JSON.stringify(skillName)}, path: './skills/${skillName}/SKILL.md' });`);
    }

    // Register hooks as pi.on() listeners
    for (const hook of extensions.hooks) {
      const eventName = hook.event.toLowerCase();
      if (hook.command) {
        extensionLines.push(`  pi.on(${JSON.stringify(eventName)}, async (event: any) => {`);
        extensionLines.push(`    const { execSync } = await import('node:child_process');`);
        extensionLines.push(`    execSync(${JSON.stringify(hook.command)}, { stdio: 'inherit' });`);
        extensionLines.push('  });');
      }
    }

    extensionLines.push('}');

    files.push({
      relativePath: 'index.ts',
      content: extensionLines.join('\n'),
      description: 'Pi Agent TypeScript Extension Entrypoint (ADR 0025)',
    });

    // 4. Trust configuration manifest
    files.push({
      relativePath: 'trust.json',
      content: JSON.stringify({ trusted: true, plugin: ir.source.pluginName }, null, 2),
      description: 'Pi Agent Trust Configuration',
    });

    return {
      targetId: this.name,
      targetName: this.displayName,
      files,
      warnings,
      manualSteps,
    };
  }
}
